language: generic
dist: trusty
sudo: false

before_install:
  - mv -f ../.emacs.d ~/.emacs.d
  - (cd $HOME/.evm && git pull) || git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

env:
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-26.2-travis
  - EVM_EMACS=emacs-26.3-travis
  - EVM_EMACS=emacs-27.1-travis-linux-xenial
  - EVM_EMACS=emacs-27.2-travis-linux-xenial
  - EVM_EMACS=emacs-git-snapshot-travis-linux-xenial

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis-linux-xenial

script:
  - emacs --version
  - emacs --batch -l init.test.el

branches:
  only:
    - master
