name: build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        emacs_version: [30.1, 30.2, release-snapshot, snapshot]
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Check out .emacs.d
        uses: actions/checkout@v5
      - name: Set up test
        run: |
          ln -s $(pwd) $HOME/.emacs.d
          emacs --version
          emacs --debug-init --batch -l init.el
