name: CI

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        emacs_version: [29.1, 29.2, 29.3, release-snapshot, snapshot]
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Check out .emacs.d
        uses: actions/checkout@v4
      - name: Set up test
        run: |
          ln -s $(pwd) $HOME/.emacs.d
          emacs --version
          emacs --debug-init --batch -l init.el
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
